#!/usr/bin/env bash

val=$(cat /sys/class/power_supply/BAT0/capacity)

if [ $val -gt 19 ]; then
    echo "(label :class \"power__text\" :text \"$val%\")"
else
    echo "(label :class \"power__text_low\" :text \"$val%\")"
fi
