#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20

bspc config border_width        3
bspc config normal_border_color "#919191"
bspc config focused_border_color "#FF6054"
bspc config presel_feedback_color "#CCCCCC"
bspc config window_gap          25

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config pointer_follows_monitor true
bspc config pointer_follows_focus false
bspc config focus_follows_pointer true

bspc config merge_overlapping_monitors true

bspc config top_monocle_padding 25
bspc config right_monocle_padding 25
bspc config left_monocle_padding 25
bspc config bottom_monocle_padding 25
bspc config borderless_monocle false

bspc rule -a Emacs state=tiled
bspc rule -a Zathura state=tiled

exec .local/bin/startup
