#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20

bspc config border_width        3
bspc config normal_border_color "#919191"
bspc config focused_border_color "#FF6054"
bspc config presel_feedback_color "#CCCCCC"
bspc config window_gap          25

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config pointer_follows_monitor true
bspc config pointer_follows_focus false
bspc config focus_follows_pointer true

exec .local/bin/startup
