import = [ "~/.config/alacritty/themes/ayu_light.toml" ]

[shell]
program = "fish"

[font]
size = 5

[font.bold]
family = "JetBrains Mono"
style = "Bold"

[font.bold_italic]
family = "JetBrains Mono"
style = "Bold Italic"

[font.italic]
family = "JetBrains Mono"
style = "Italic"

[font.normal]
family = "JetBrains Mono"
style = "SemiBold"

[window]
padding = { x = 5, y = 5 }

[cursor]
thickness = 0.1

[mouse]
hide_when_typing = true